sudo: false
language: java
jdk: oraclejdk8
cache:
    directories:
        - .gradle
        - $HOME/.gradle
branches:
    only: master
after_success:
    - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && ./gradlew githubRelease || false'
